spring.application.name=smartpass

spring.datasource.url=jdbc:mysql://localhost:3306/smartpass
spring.datasource.username=root
spring.datasource.password=Ksree@06

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

